export const KPI_CARDS_CONFIG = [
  {
    key: 'totalNotifications',
    label: 'Total Notifications',
    textColor: 'text-[#2563EB]',
    iconBg: 'bg-[#DBEAFE]',
    bgColor: 'bg-gradient-to-br from-[#EFF6FF] to-[#DBEAFE]/40',
    borderColor: 'border-[#BFDBFE]',
    icon: '📊',
  },
  {
    key: 'notif15Days',
    label: 'Notif > 15 days',
    textColor: 'text-[#7C3AED]',
    iconBg: 'bg-[#EDE9FE]',
    bgColor: 'bg-gradient-to-br from-[#F5F3FF] to-[#EDE9FE]/40',
    borderColor: 'border-[#DDD6FE]',
    icon: '⏱️',
  },
  {
    key: 'impactedUnits',
    label: 'Units impacted',
    textColor: 'text-[#DC2626]',
    iconBg: 'bg-[#FEE2E2]',
    bgColor: 'bg-gradient-to-br from-[#FEF2F2] to-[#FEE2E2]/40',
    borderColor: 'border-[#FECACA]',
    icon: '🏭',
  },
  {
    key: 'm2Pending',
    label: 'M2 Pending > 7 days',
    textColor: 'text-[#EA580C]',
    iconBg: 'bg-[#FFEDD5]',
    bgColor: 'bg-gradient-to-br from-[#FFF7ED] to-[#FFEDD5]/40',
    borderColor: 'border-[#FED7AA]',
    icon: '⏳',
  },
  {
    key: 'm1Pending',
    label: 'M1 Pending > 25 days',
    textColor: 'text-[#D97706]',
    iconBg: 'bg-[#FEF3C7]',
    bgColor: 'bg-gradient-to-br from-[#FFFBEB] to-[#FEF3C7]/40',
    borderColor: 'border-[#FDE68A]',
    icon: '⚠️',
  },
];
