export const KPI_CARDS_CONFIG = [
  {
    key: 'totalNotifications',
    label: 'Total Notifications',
    textColor: 'text-[#005A9C]',
    leftBorderColor: 'border-l-[#005A9C]',
    iconBg: 'bg-[#DBEAFE]',
    bgColor: 'bg-gradient-to-br from-[#EFF6FF] to-[#DBEAFE]/40',
    borderColor: 'border-[#BFDBFE]',
    icon: '📊',
  },
  {
    key: 'impactedUnits',
    label: 'Units impacted',
    textColor: 'text-[#0F172A]',
    leftBorderColor: 'border-l-[#EAB308]',
    iconBg: 'bg-[#FEF9C3]',
    bgColor: 'bg-gradient-to-br from-[#FEFCE8] to-[#FEF9C3]/40',
    borderColor: 'border-[#FEF08A]',
    icon: '🏭',
  },
  {
    key: 'notif15Days',
    label: 'Notif > 15 days',
    textColor: 'text-[#16A34A]',
    leftBorderColor: 'border-l-[#16A34A]',
    iconBg: 'bg-[#EDE9FE]',
    bgColor: 'bg-gradient-to-br from-[#F5F3FF] to-[#EDE9FE]/40',
    borderColor: 'border-[#DDD6FE]',
    icon: '⏱️',
  },
  {
    key: 'm2Pending',
    label: 'M2 Pending > 7 days',
    textColor: 'text-[#DC2626]',
    leftBorderColor: 'border-l-[#DC2626]',
    iconBg: 'bg-[#FEE2E2]',
    bgColor: 'bg-gradient-to-br from-[#FEF2F2] to-[#FEE2E2]/40',
    borderColor: 'border-[#FECACA]',
    icon: '⏳',
  },
  {
    key: 'm1Pending',
    label: 'M1 Pending > 25 days',
    textColor: 'text-[#EA580C]',
    leftBorderColor: 'border-l-[#EA580C]',
    iconBg: 'bg-[#FFEDD5]',
    bgColor: 'bg-gradient-to-br from-[#FFF7ED] to-[#FFEDD5]/40',
    borderColor: 'border-[#FED7AA]',
    icon: '⚠️',
  },
];
